### ISSUE TITLE
python API

### ISSUE THREAD

**Issue by joamatab** [Coloquinte/PlaceRoute#1]
Hi Gabriel,

how could make this place and route available on PyPi?

this way we could use it from [gdsfactory](https://gdsfactory.github.io/gdsfactory/README.html) python driven flow

**Comment by Coloquinte** [comment]
Hi Joannes,

I am currently writing a Pybind11 interface, so it could be available on PyPi in the next few days - it's as painful as I remembered, but it's starting to work.

Actually I started writing the interface to simplify benchmarking - and I have a lot of benchmarking to do to make it work best for all circuits. I was wondering: being at Google, would you have some compute resources to spare by any chance?

Regards,
Gabriel

**Comment by joamatab** [comment]
What code do you want to run?

@proppy

**Comment by proppy** [comment]
@Coloquinte sure, you could contact me over email (my username @ my employer.com) about this?

For the Python bindings, which API did you had in mind? OpenROAD is going thru a similar exercise here:
https://github.com/The-OpenROAD-Project/OpenROAD/issues/1812
https://github.com/The-OpenROAD-Project/OpenROAD/pull/1849
and it'd be great to swap notes.

**Comment by Coloquinte** [comment]
Hi!

Thanks :) I'll contact you shortly

Coloquinte is just a placement component, so I'm aiming for something much simpler than a full-fledged LEFDEF wrapper. It's going to evolve with the tool - we're gonna need routing and timing callbacks at some point - but my first draft is on the python_module branch

**Comment by Coloquinte** [comment]
I want to run benchmarks for parameter tuning - setting up the default parameters for each optimization effort so we have a good quality/runtime tradeoff

**Comment by Coloquinte** [comment]
Hi!

I'm done with the Python package. It's not yet suitable for distribution on PyPi - I need to setup the manylinux docker and do a Windows build for that - but you can install it locally with `python setup.py install` in the pycoloquinte directory

**Comment by proppy** [comment]
> I need to setup the manylinux docker and do a Windows build for that

Did you look into https://github.com/pypa/cibuildwheel ?

**Comment by Coloquinte** [comment]
Very nice! I'll have a look. Thanks

**Comment by Coloquinte** [comment]
manylinux2014_x86_64 wheels are now available. You should be able to install them with pip install coloquinte

cibuildwheel seems to get stuck https://github.com/Coloquinte/PlaceRoute/actions/runs/3076347184/jobs/4970434651

If you are motivated, don't hesitate to play with more platforms, but I'm giving up for now - eigen3 + boost dependencies are a pain to automate.

**Comment by proppy** [comment]
@msaligane fyi
