### ISSUE TITLE
Sign compare warnings with gcc

### ISSUE THREAD

**Issue by robtaylor** [Coloquinte/PlaceRoute#8]
../../subprojects/coloquinte/src/place_detailed/place_detailed.cpp: In member function ‘void coloquinte::RowReordering::runRegionChoice(int)’:
../../subprojects/coloquinte/src/place_detailed/place_detailed.cpp:690:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  690 |     for (int i = 0; i < nbRegions(); ++i) {
      |                     ~~^~~~~~~~~~~~~
[23/1078] Compiling C++ object subprojects/coloquinte/libcoloquinte.so.p/src_place_global_transportation.cpp.o
../../subprojects/coloquinte/src/place_global/transportation.cpp: In member function ‘void coloquinte::TransportationProblem::check() const’:
../../subprojects/coloquinte/src/place_global/transportation.cpp:177:23: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  177 |   if (demands_.size() != nbSources()) {
      |       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation.cpp:180:26: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  180 |   if (capacities_.size() != nbSinks()) {
      |       ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation.cpp:194:21: warning: comparison of integer expressions of different signedness: ‘std::vector<std::vector<int> >::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  194 |   if (costs_.size() != nbSinks()) {
      |       ~~~~~~~~~~~~~~^~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation.cpp:199:18: warning: comparison of integer expressions of different signedness: ‘std::vector<int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  199 |     if (c.size() != nbSources()) {
      |         ~~~~~~~~~^~~~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation.cpp:205:27: warning: comparison of integer expressions of different signedness: ‘std::vector<std::vector<long long int> >::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  205 |   if (allocations_.size() != nbSinks()) {
      |       ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation.cpp:210:18: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  210 |     if (c.size() != nbSources()) {
      |         ~~~~~~~~~^~~~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation.cpp: In member function ‘void coloquinte::TransportationProblem::setAssignment(const std::vector<int>&)’:
../../subprojects/coloquinte/src/place_global/transportation.cpp:378:25: warning: comparison of integer expressions of different signedness: ‘std::vector<int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  378 |   if (assignment.size() > nbSources()) {
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
[24/1078] Compiling C++ object subprojects/coloquinte/libcoloquinte.so.p/src_place_global_transportation_1d.cpp.o
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp: In member function ‘Transportation1d::Solution Transportation1dSolver::computeSolution() const’:
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:297:12: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  297 |   while (i < p.size() && j < nbSinks()) {
      |          ~~^~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp: In member function ‘std::vector<int> Transportation1dSolver::computeAssignment() const’:
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:319:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  319 |   for (int i = 0; i < p.size(); ++i) {
      |                   ~~^~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp: In member function ‘void Transportation1dSolver::check() const’:
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:396:16: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  396 |   if (S.size() != nbSources() + 1) {
      |       ~~~~~~~~~^~~~~~~~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:399:16: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  399 |   if (D.size() != nbSinks() + 1) {
      |       ~~~~~~~~~^~~~~~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:402:16: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  402 |   if (p.size() > nbSources()) {
      |       ~~~~~~~~~^~~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp: In member function ‘void Transportation1d::check() const’:
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:410:16: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  410 |   if (u.size() != nbSources()) {
      |       ~~~~~~~~~^~~~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:413:16: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  413 |   if (v.size() != nbSinks()) {
      |       ~~~~~~~~~^~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:416:16: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  416 |   if (s.size() != nbSources()) {
      |       ~~~~~~~~~^~~~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:419:16: warning: comparison of integer expressions of different signedness: ‘std::vector<long long int>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  419 |   if (d.size() != nbSinks()) {
      |       ~~~~~~~~~^~~~~~~~~~~~
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp: In static member function ‘static void Transportation1d::writeAssignment(const std::vector<int>&, std::ostream&)’:
../../subprojects/coloquinte/src/place_global/transportation_1d.cpp:580:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<int>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  580 |   for (int i = 0; i < sol.size(); ++i) {
      |                   ~~^~~~~~~~~~~~
[33/1078] Compiling C++ object subprojects/coloquinte/test_row_legalizer.p/test_test_row_legalizer.cpp.o
../../subprojects/coloquinte/test/test_row_legalizer.cpp: In function ‘int computeCost(const std::vector<int>&, const std::vector<int>&, const std::vector<int>&)’:
../../subprojects/coloquinte/test/test_row_legalizer.cpp:114:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<int>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  114 |   for (int i = 0; i < widths.size(); ++i) {
      |                   ~~^~~~~~~~~~~~~~~
../../subprojects/coloquinte/test/test_row_legalizer.cpp: In function ‘void fuzzRowLegalizer(int, int, const std::vector<int>&, const std::vector<int>&)’:
../../subprojects/coloquinte/test/test_row_legalizer.cpp:126:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<int>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  126 |   for (int i = 0; i < widths.size(); ++i) {

**Comment by Coloquinte** [comment]
Should be fixed now. Not entirely clean, as it's mostly explicit casting
